Wicked nm migration add bonding again
jcronenberg/agama pull request #57
Opened 2023-12-20 16:52 UTC by cfconrad

## Problem

Upstream bonding was finally merged and now we can re-implement the migrate-wicked side.

## Testing

- *Added a new unit test*

2024-01-04 13:08 UTC, jcronenberg requested changes

2024-01-04 16:05 UTC, jcronenberg commented on rust/migrate-wicked/src/migrate.rs
> +        }
Nvm, after thinking about it a bit more, I dislike my version more and I don't see any benefit :slightly_smiling_face:

2024-01-08 15:44 UTC, cfconrad commented on rust/migrate-wicked/src/interface.rs
>          };
WDYT of 
```rust
impl TryFrom<&Option<String>> for MacAddress {
    type Error = InvalidMacAddress;

    fn try_from(value: &Option<String>) -> Result<Self, Self::Error> {
        match &value {
            Some(str) => MacAddress::from_str(str),
            None => Ok(Self::Unset)
        }
    }
}
```

2024-01-08 15:48 UTC, jcronenberg commented on rust/migrate-wicked/src/interface.rs
>          };
Sure, should also work if you prefer it.

2024-01-09 15:56 UTC, cfconrad commented on rust/migrate-wicked/src/interface.rs
>          };
I finally go with 
```
#serde(default)
address: String,
```
which lead to empty string if it isn't in xml...

2024-01-09 16:08 UTC, jcronenberg commented on rust/migrate-wicked/src/interface.rs
>          };
> I finally go with
> 
> ```
> #serde(default)
> address: String,
> ```
> 
> which lead to empty string if it isn't in xml...

In that case you should also add
```rust
#[serde(skip_serializing_if = "String::is_empty")]
```

2024-01-09 16:15 UTC, cfconrad commented on rust/migrate-wicked/src/interface.rs
>          };
valid point. 

Lets see if this https://github.com/openSUSE/agama/pull/983 gets accepted, maybe I go back to `Option<String>`

2024-01-10 12:29 UTC, jcronenberg approved these changes

2024-01-10 12:30 UTC, merged